language: rust
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

services:
  - docker

rust:
- stable
- beta
- nightly

cache:
  directories:
    - $HOME/.cargo
    - target

#   image: quay.io/coreos/etcd:v2.2.4
#  restart: always
#  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
before_install:
- docker pull quay.io/coreos/etcd:v2.2.4
- docker run -d -p 2379 quay.io/coreos/etcd:v2.2.4 -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
- until curl -vsi http://localhost:2379/health; do echo "running for: $SECONDS"; sleep 1; done

install:
  - env

before_script:
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - RUST_BACKTRACE=t

script:
- travis-cargo build
- travis-cargo test

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
