language: rust
sudo: false
language: rust
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - minisat

rust:
- stable
- beta
- nightly

cache:
  directories:
    - $HOME/.cargo
    - target

install:
  - env

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - RUST_BACKTRACE=t

script:
- travis-cargo build
- travis-cargo test

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
