# Scan this file for changes every 30 seconds
refresh_rate = 1

# An appender named "stdout" that writes to stdout
[appenders.stdout]
kind = "console"
pattern = "%d{%Y-%m-%dT%H:%M:%S.%f%z} [%t] %l {%T}: %m"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
[root]
level = "info"
appenders = ["stdout"]

# and *not* the normal appenders installed at the root
[[logger]]
name = "chain_repl_test"
level = "warn"

[[logger]]
name = "chain_repl_test::replication_log"
level = "warn"

[[logger]]
name = "chain_repl_test::config"
level = "warn"
