# Scan this file for changes every 30 seconds
refresh_rate = 3600

# An appender named "stdout" that writes to stdout
[appender.stdout]
kind = "console"
pattern = "%d{%Y-%m-%dT%H:%M:%S.%f%z} [%t] %l {%T}: %m"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
[root]
level = "debug"
appenders = ["stdout"]
